"""PostgreSQL-only, opt-in local document knowledge base.

Documents are ingested through descriptor-pinned Linux HOME access.
Nothing is automatically collected, embedded, uploaded, or sent to the model.
"""
import hashlib
import os
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from threading import RLock

import psycopg

from nexus.config.settings import Settings
from nexus.database.errors import DatabaseConfigurationError, DatabaseLifecycleError
from nexus.security.paths import PathSecurity


class KnowledgeValidationError(ValueError):
    """An invalid document, search or identifier was supplied."""


class KnowledgeStoreError(RuntimeError):
    """Sanitized failure; document content and credentials are never in the message."""


@dataclass(frozen=True)
class KnowledgeDocument:
    id: int
    name: str
    source_path: str
    sha256: str
    chunk_count: int
    created_at: datetime
    added: bool = False


@dataclass(frozen=True)
class KnowledgeHit:
    document_id: int
    chunk_id: int
    name: str
    ordinal: int
    text: str


class PostgreSQLKnowledgeBase:
    """Local, explicitly ingested text, indexed with built-in PostgreSQL FTS."""

    MAX_BYTES = 256 * 1024
    MAX_CHARS = 256 * 1024
    CHUNK_CHARS = 1000
    CHUNK_OVERLAP = 100
    MAX_CHUNKS = 320
    MAX_RESULTS = 20
    ALLOWED_EXTENSIONS = frozenset({".txt", ".md"})

    def __init__(self, settings: Settings, path_security: PathSecurity | None = None):
        if settings.database_provider != "postgresql":
            raise DatabaseConfigurationError("A base de conhecimento exige PostgreSQL.")
        if settings.database_host not in ("127.0.0.1", "localhost", "::1"):
            raise DatabaseConfigurationError("PostgreSQL deve usar loopback local.")
        if not settings.database_password:
            raise DatabaseConfigurationError("NEXUS_DATABASE_PASSWORD é obrigatório.")
        self._settings = settings
        self._paths = path_security if path_security is not None else PathSecurity()
        self._connection = None
        self._lock = RLock()

    @property
    def initialized(self) -> bool:
        return self._connection is not None

    def initialize(self) -> None:
        with self._lock:
            if self._connection is not None:
                raise DatabaseLifecycleError("Base de conhecimento já inicializada.")
            cfg = self._settings
            try:
                conn = psycopg.connect(
                    host=cfg.database_host, port=cfg.database_port,
                    dbname=cfg.database_name, user=cfg.database_user,
                    password=cfg.database_password,
                    connect_timeout=cfg.database_connect_timeout,
                )
            except psycopg.Error as exc:
                raise KnowledgeStoreError("Conexão local PostgreSQL indisponível.") from exc
            try:
                with conn.cursor() as cursor:
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS nexus_knowledge_documents (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name TEXT NOT NULL,
                            source_path TEXT NOT NULL,
                            sha256 CHAR(64) NOT NULL UNIQUE,
                            chunk_count INTEGER NOT NULL CHECK (chunk_count BETWEEN 1 AND 320),
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                    """)
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS nexus_knowledge_chunks (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            document_id BIGINT NOT NULL REFERENCES nexus_knowledge_documents(id)
                                ON DELETE CASCADE,
                            ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
                            body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 1000),
                            UNIQUE (document_id, ordinal)
                        )
                    """)
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS nexus_knowledge_fts_idx
                        ON nexus_knowledge_chunks USING GIN (to_tsvector('simple', body))
                    """)
                    cursor.execute("""
                        CREATE TABLE IF NOT EXISTS nexus_knowledge_audit (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(12) NOT NULL
                                CHECK (action IN ('IMPORT', 'DUPLICATE', 'LIST',
                                                  'SEARCH', 'DELETE', 'CONTEXT')),
                            document_id BIGINT,
                            affected_count INTEGER NOT NULL DEFAULT 0
                                CHECK (affected_count >= 0),
                            occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                    """)
                conn.commit()
            except psycopg.Error as exc:
                conn.rollback()
                conn.close()
                raise KnowledgeStoreError("Falha ao inicializar esquema PostgreSQL de conhecimento.") from exc
            self._connection = conn

    def close(self) -> None:
        with self._lock:
            if self._connection is not None:
                self._connection.close()
                self._connection = None

    @staticmethod
    def _positive_id(value: int) -> int:
        if type(value) is not int or value < 1:
            raise KnowledgeValidationError("O identificador deve ser inteiro positivo.")
        return value

    @classmethod
    def _valid_limit(cls, limit) -> int:
        if type(limit) is not int or not 1 <= limit <= cls.MAX_RESULTS:
            raise KnowledgeValidationError("Limite de resultados inválido (1 a 20).")
        return limit

    @staticmethod
    def _valid_query(query: str) -> str:
        if not isinstance(query, str) or not query.strip() or len(query.strip()) > 160 or "\x00" in query:
            raise KnowledgeValidationError("Pesquisa deve conter de 1 a 160 caracteres.")
        return query.strip()

    def _transaction(self, callback):
        with self._lock:
            if self._connection is None:
                raise DatabaseLifecycleError("Base de conhecimento não inicializada.")
            try:
                with self._connection.cursor() as cursor:
                    value = callback(cursor)
                self._connection.commit()
                return value
            except psycopg.Error as exc:
                self._connection.rollback()
                raise KnowledgeStoreError("Falha na operação de conhecimento PostgreSQL.") from exc
            except Exception:
                self._connection.rollback()
                raise

    @staticmethod
    def _audit(cursor, action: str, document_id=None, count=0) -> None:
        cursor.execute(
            "INSERT INTO nexus_knowledge_audit (action, document_id, affected_count) "
            "VALUES (%s, %s, %s)",
            (action, document_id, count),
        )

    def _read_file(self, path: str | Path) -> tuple[str, str, str]:
        if not isinstance(path, (str, Path)) or not os.fspath(path):
            raise KnowledgeValidationError("Caminho do documento inválido.")
        candidate = Path(path).expanduser()
        if candidate.suffix.lower() not in self.ALLOWED_EXTENSIONS:
            raise KnowledgeValidationError("Aceitos somente arquivos .txt e .md.")
        try:
            # Security policy guards HOME/private dirs and every component
            # uses O_NOFOLLOW; read from the authorized file descriptor only.
            with self._paths.open_regular_file(candidate) as (fd, authorized_path):
                if os.fstat(fd).st_size > self.MAX_BYTES:
                    raise KnowledgeValidationError("Arquivo maior que 256 KiB.")
                payload = bytearray()
                while len(payload) <= self.MAX_BYTES:
                    part = os.read(fd, min(65536, self.MAX_BYTES + 1 - len(payload)))
                    if not part:
                        break
                    payload.extend(part)
        except (OSError, PermissionError) as exc:
            raise KnowledgeValidationError("Arquivo inexistente, protegido ou inacessível.") from exc
        if len(payload) > self.MAX_BYTES or not payload:
            raise KnowledgeValidationError("Arquivo vazio ou acima de 256 KiB.")
        try:
            text = bytes(payload).decode("utf-8").replace("\r\n", "\n").strip()
        except UnicodeDecodeError as exc:
            raise KnowledgeValidationError("O documento precisa ser UTF-8.") from exc
        if not text or "\x00" in text or len(text) > self.MAX_CHARS:
            raise KnowledgeValidationError("Conteúdo vazio, binário ou acima do limite.")
        return authorized_path.name, str(authorized_path), text

    @classmethod
    def _chunks(cls, text: str) -> list[str]:
        step = cls.CHUNK_CHARS - cls.CHUNK_OVERLAP
        chunks = [text[start:start + cls.CHUNK_CHARS]
                  for start in range(0, len(text), step)]
        if len(chunks) > cls.MAX_CHUNKS:
            raise KnowledgeValidationError("Documento excede 320 trechos.")
        return chunks

    @staticmethod
    def _document(row, added=False):
        return KnowledgeDocument(
            id=int(row[0]), name=row[1], source_path=row[2],
            sha256=row[3].strip(), chunk_count=int(row[4]),
            created_at=row[5], added=added,
        )

    def ingest(self, path: str | Path) -> KnowledgeDocument:
        name, source_path, text = self._read_file(path)
        chunks = self._chunks(text)
        digest = hashlib.sha256(text.encode("utf-8")).hexdigest()

        def action(cursor):
            cursor.execute(
                "INSERT INTO nexus_knowledge_documents "
                "(name, source_path, sha256, chunk_count) VALUES (%s, %s, %s, %s) "
                "ON CONFLICT (sha256) DO NOTHING "
                "RETURNING id, name, source_path, sha256, chunk_count, created_at",
                (name, source_path, digest, len(chunks)),
            )
            row = cursor.fetchone()
            if row is None:
                cursor.execute(
                    "SELECT id, name, source_path, sha256, chunk_count, created_at "
                    "FROM nexus_knowledge_documents WHERE sha256 = %s",
                    (digest,),
                )
                old = cursor.fetchone()
                self._audit(cursor, "DUPLICATE", document_id=old[0])
                return self._document(old)
            for ordinal, body in enumerate(chunks):
                cursor.execute(
                    "INSERT INTO nexus_knowledge_chunks (document_id, ordinal, body) "
                    "VALUES (%s, %s, %s)",
                    (row[0], ordinal, body),
                )
            self._audit(cursor, "IMPORT", document_id=row[0], count=len(chunks))
            return self._document(row, added=True)

        return self._transaction(action)

    def list_documents(self, limit=20) -> list[KnowledgeDocument]:
        max_rows = self._valid_limit(limit)

        def action(cursor):
            cursor.execute(
                "SELECT id, name, source_path, sha256, chunk_count, created_at "
                "FROM nexus_knowledge_documents ORDER BY id DESC LIMIT %s",
                (max_rows,),
            )
            rows = cursor.fetchall()
            self._audit(cursor, "LIST", count=len(rows))
            return [self._document(row) for row in rows]

        return self._transaction(action)

    def search(self, query: str, limit=5, *, for_context=False) -> list[KnowledgeHit]:
        term = self._valid_query(query)
        max_rows = self._valid_limit(limit)
        # Escape LIKE metacharacters with !, not backslash; never interpolate into SQL.
        escaped = term.replace("!", "!!").replace("%", "!%").replace("_", "!_")
        pattern = "%" + escaped + "%"

        def action(cursor):
            cursor.execute("""
                SELECT d.id, c.id, d.name, c.ordinal, c.body
                FROM nexus_knowledge_chunks c
                JOIN nexus_knowledge_documents d ON d.id = c.document_id
                WHERE to_tsvector('simple', c.body) @@ plainto_tsquery('simple', %s)
                   OR c.body ILIKE %s ESCAPE '!'
                ORDER BY
                    ts_rank(to_tsvector('simple', c.body),
                            plainto_tsquery('simple', %s)) DESC,
                    d.id DESC, c.ordinal ASC
                LIMIT %s
            """, (term, pattern, term, max_rows))
            rows = cursor.fetchall()
            self._audit(cursor, "CONTEXT" if for_context else "SEARCH", count=len(rows))
            return [KnowledgeHit(int(r[0]), int(r[1]), r[2], int(r[3]), r[4])
                    for r in rows]

        return self._transaction(action)

    def delete(self, document_id: int) -> bool:
        identifier = self._positive_id(document_id)

        def action(cursor):
            cursor.execute("DELETE FROM nexus_knowledge_documents WHERE id = %s",
                           (identifier,))
            deleted = cursor.rowcount == 1
            self._audit(cursor, "DELETE", document_id=identifier, count=int(deleted))
            return deleted

        return self._transaction(action)
