from unittest.mock import MagicMock

import psycopg
import pytest

from nexus.database.errors import (
    DatabaseConnectionError,
    DatabaseLifecycleError,
    DatabaseOperationError,
)
from nexus.database.postgresql import PostgreSQLProvider


def build_provider(password="secret"):
    return PostgreSQLProvider(
        host="127.0.0.1",
        port=5432,
        database="nexus",
        user="nexus",
        password=password,
        connect_timeout=5,
    )


def test_construction_does_not_connect(monkeypatch):
    def forbidden_connect(**kwargs):
        raise AssertionError("construction must not connect")

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        forbidden_connect,
    )

    provider = build_provider()

    assert provider.provider_id == "postgresql"
    assert provider.initialized is False


def test_initialize_connects_with_explicit_parameters(monkeypatch):
    connection = MagicMock()
    calls = []

    def fake_connect(**kwargs):
        calls.append(kwargs)
        return connection

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        fake_connect,
    )

    provider = build_provider(password="test-password")
    provider.initialize()

    assert provider.initialized is True
    assert calls == [
        {
            "host": "127.0.0.1",
            "port": 5432,
            "dbname": "nexus",
            "user": "nexus",
            "password": "test-password",
            "connect_timeout": 5,
        }
    ]


def test_initialize_rejects_double_initialization(monkeypatch):
    connection = MagicMock()

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    with pytest.raises(
        DatabaseLifecycleError,
        match="já foi inicializado",
    ):
        provider.initialize()


def test_initialize_maps_connection_error_without_password(monkeypatch):
    password = "never-expose-this-password"

    def failing_connect(**kwargs):
        raise psycopg.OperationalError(
            "simulated connection failure"
        )

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        failing_connect,
    )

    provider = build_provider(password=password)

    with pytest.raises(DatabaseConnectionError) as exc_info:
        provider.initialize()

    assert str(exc_info.value) == (
        "Falha ao conectar ao PostgreSQL"
    )
    assert password not in str(exc_info.value)
    assert provider.initialized is False


def test_healthcheck_requires_initialization():
    provider = build_provider()

    with pytest.raises(
        DatabaseLifecycleError,
        match="não foi inicializado",
    ):
        provider.healthcheck()


def test_healthcheck_executes_select_one(monkeypatch):
    connection = MagicMock()
    schema_cursor = MagicMock()
    health_cursor = MagicMock()

    connection.cursor.return_value.__enter__.side_effect = [
        schema_cursor,
        health_cursor,
    ]
    health_cursor.fetchone.return_value = (1,)

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    assert provider.healthcheck() is True
    health_cursor.execute.assert_called_once_with("SELECT 1")


def test_close_is_idempotent(monkeypatch):
    connection = MagicMock()

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    provider.close()
    provider.close()

    connection.close.assert_called_once_with()
    assert provider.initialized is False

def test_initialize_creates_system_events_schema(monkeypatch):
    connection = MagicMock()
    cursor = MagicMock()

    connection.cursor.return_value.__enter__.return_value = cursor

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    executed_sql = cursor.execute.call_args.args[0]

    assert "CREATE TABLE IF NOT EXISTS system_events" in executed_sql
    assert (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        in executed_sql
    )
    assert "event_type TEXT NOT NULL" in executed_sql
    assert "message TEXT NOT NULL" in executed_sql
    assert (
        "created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP"
        in executed_sql
    )
    connection.commit.assert_called_once_with()


def test_initialize_rolls_back_and_closes_when_schema_creation_fails(
    monkeypatch,
):
    connection = MagicMock()
    cursor = MagicMock()

    connection.cursor.return_value.__enter__.return_value = cursor
    cursor.execute.side_effect = psycopg.ProgrammingError(
        "simulated schema failure"
    )

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()

    with pytest.raises(
        DatabaseOperationError,
        match="inicializar schema",
    ):
        provider.initialize()

    connection.rollback.assert_called_once_with()
    connection.close.assert_called_once_with()
    assert provider.initialized is False


def test_add_event_requires_initialization():
    provider = build_provider()

    with pytest.raises(
        DatabaseLifecycleError,
        match="não foi inicializado",
    ):
        provider.add_event(
            "system.start",
            "Nexus Core inicializado",
        )


def test_add_event_uses_parameter_binding_and_commits(monkeypatch):
    connection = MagicMock()
    schema_cursor = MagicMock()
    event_cursor = MagicMock()

    connection.cursor.return_value.__enter__.side_effect = [
        schema_cursor,
        event_cursor,
    ]

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    provider.add_event(
        "system.start",
        "Nexus Core inicializado",
    )

    event_cursor.execute.assert_called_once_with(
        """
            INSERT INTO system_events (event_type, message)
            VALUES (%s, %s)
            """,
        (
            "system.start",
            "Nexus Core inicializado",
        ),
    )

    assert connection.commit.call_count == 2


def test_add_event_rolls_back_on_database_error(monkeypatch):
    connection = MagicMock()
    schema_cursor = MagicMock()
    event_cursor = MagicMock()

    connection.cursor.return_value.__enter__.side_effect = [
        schema_cursor,
        event_cursor,
    ]

    event_cursor.execute.side_effect = psycopg.DatabaseError(
        "simulated insert failure"
    )

    monkeypatch.setattr(
        "nexus.database.postgresql.psycopg.connect",
        lambda **kwargs: connection,
    )

    provider = build_provider()
    provider.initialize()

    with pytest.raises(
        DatabaseOperationError,
        match="persistir evento",
    ):
        provider.add_event(
            "system.start",
            "Nexus Core inicializado",
        )

    connection.rollback.assert_called_once_with()









