import psycopg
from psycopg import Connection

from nexus.database.errors import (
    DatabaseConnectionError,
    DatabaseLifecycleError,
    DatabaseOperationError,
)


class PostgreSQLProvider:
    """
    Provider PostgreSQL do Nexus Core.

    A construção do objeto não realiza I/O. A conexão é
    estabelecida explicitamente por initialize().
    """

    provider_id = "postgresql"

    def __init__(
        self,
        *,
        host: str,
        port: int,
        database: str,
        user: str,
        password: str,
        connect_timeout: float,
    ):
        self._host = host
        self._port = port
        self._database = database
        self._user = user
        self._password = password
        self._connect_timeout = connect_timeout
        self._connection: Connection | None = None

    @property
    def initialized(self) -> bool:
        return self._connection is not None

    def initialize(self) -> None:
        if self._connection is not None:
            raise DatabaseLifecycleError(
                "PostgreSQLProvider já foi inicializado"
            )

        try:
            connection = psycopg.connect(
                host=self._host,
                port=self._port,
                dbname=self._database,
                user=self._user,
                password=self._password,
                connect_timeout=self._connect_timeout,
            )
        except psycopg.Error as exc:
            raise DatabaseConnectionError(
                "Falha ao conectar ao PostgreSQL"
            ) from exc

        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS system_events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        event_type TEXT NOT NULL,
                        message TEXT NOT NULL,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                    )
                    """
                )

            connection.commit()
        except psycopg.Error as exc:
            connection.rollback()
            connection.close()

            raise DatabaseOperationError(
                "Falha ao inicializar schema PostgreSQL"
            ) from exc

        self._connection = connection

    def healthcheck(self) -> bool:
        if self._connection is None:
            raise DatabaseLifecycleError(
                "PostgreSQLProvider não foi inicializado"
            )

        try:
            with self._connection.cursor() as cursor:
                cursor.execute("SELECT 1")
                row = cursor.fetchone()
        except psycopg.Error as exc:
            raise DatabaseConnectionError(
                "Falha no healthcheck do PostgreSQL"
            ) from exc

        return row == (1,)

    def add_event(
        self,
        event_type: str,
        message: str,
    ) -> None:
        if self._connection is None:
            raise DatabaseLifecycleError(
                "PostgreSQLProvider não foi inicializado"
            )

        try:
            with self._connection.cursor() as cursor:
                cursor.execute(
                    """
            INSERT INTO system_events (event_type, message)
            VALUES (%s, %s)
            """,
                    (
                        event_type,
                        message,
                    ),
                )

            self._connection.commit()
        except psycopg.Error as exc:
            self._connection.rollback()

            raise DatabaseOperationError(
                "Falha ao persistir evento no PostgreSQL"
            ) from exc

    def close(self) -> None:
        if self._connection is None:
            return

        self._connection.close()
        self._connection = None
