"""Explicit, time-limited local memories stored in PostgreSQL, never SQLite.

No chat messages are persisted automatically. Memory audit records contain
only action metadata and affected counts, not the stored content or queries.
"""

from dataclasses import dataclass
from datetime import datetime
from threading import RLock

import psycopg

from nexus.config.settings import Settings
from nexus.database.errors import DatabaseConfigurationError, DatabaseLifecycleError


class MemoryValidationError(ValueError):
    """A caller supplied an invalid memory, identifier, limit or retention."""


class MemoryStoreError(RuntimeError):
    """Sanitized PostgreSQL failure: never expose credentials or memory text."""


@dataclass(frozen=True)
class MemoryEntry:
    id: int
    content: str
    created_at: datetime
    expires_at: datetime

    @classmethod
    def from_row(cls, row):
        return cls(int(row[0]), row[1], row[2], row[3])


class PostgreSQLMemoryStore:
    """Bounded, explicit personal memory operations with metadata-only auditing."""

    MAX_LENGTH = 1200
    MAX_RETENTION_DAYS = 365
    DEFAULT_RETENTION_DAYS = 90
    MAX_RESULTS = 100

    def __init__(self, settings: Settings):
        if settings.database_provider != "postgresql":
            raise DatabaseConfigurationError("Memória exige PostgreSQL.")
        if settings.database_host not in ("127.0.0.1", "localhost", "::1"):
            raise DatabaseConfigurationError("PostgreSQL deve ser local.")
        if not settings.database_password:
            raise DatabaseConfigurationError("NEXUS_DATABASE_PASSWORD é obrigatório.")
        self._settings = settings
        self._connection = None
        self._lock = RLock()

    @property
    def initialized(self) -> bool:
        return self._connection is not None

    def initialize(self) -> None:
        with self._lock:
            if self._connection is not None:
                raise DatabaseLifecycleError("Memória já foi inicializada.")
            s = self._settings
            try:
                conn = psycopg.connect(
                    host=s.database_host,
                    port=s.database_port,
                    dbname=s.database_name,
                    user=s.database_user,
                    password=s.database_password,
                    connect_timeout=s.database_connect_timeout,
                )
            except psycopg.Error as exc:
                raise MemoryStoreError("Não foi possível conectar ao PostgreSQL local.") from exc
            try:
                with conn.cursor() as cursor:
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS nexus_memories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            content TEXT NOT NULL
                                CHECK (char_length(content) BETWEEN 1 AND 1200),
                            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            expires_at TIMESTAMPTZ NOT NULL,
                            CHECK (expires_at > created_at)
                        )
                        """
                    )
                    cursor.execute(
                        "CREATE INDEX IF NOT EXISTS nexus_memories_expiry_idx "
                        "ON nexus_memories (expires_at)"
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS nexus_memory_audit (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(16) NOT NULL
                                CHECK (action IN ('ADD', 'SEARCH', 'LIST', 'DELETE',
                                                  'CLEAR', 'EXPIRE', 'STATUS')),
                            memory_id BIGINT,
                            affected_count INTEGER NOT NULL DEFAULT 0
                                CHECK (affected_count >= 0),
                            occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
                        )
                        """
                    )
                conn.commit()
            except psycopg.Error as exc:
                conn.rollback()
                conn.close()
                raise MemoryStoreError("Não foi possível inicializar o schema de memórias.") from exc
            self._connection = conn

    def close(self) -> None:
        with self._lock:
            if self._connection is not None:
                self._connection.close()
                self._connection = None

    @staticmethod
    def _positive_int(value, name, maximum=None) -> int:
        if type(value) is not int or value <= 0 or (maximum is not None and value > maximum):
            raise MemoryValidationError(f"{name} precisa ser inteiro positivo dentro do limite.")
        return value

    @classmethod
    def _validate_content(cls, content):
        if not isinstance(content, str) or not content.strip():
            raise MemoryValidationError("O conteúdo da memória não pode ser vazio.")
        text = content.strip()
        if len(text) > cls.MAX_LENGTH or "\x00" in text:
            raise MemoryValidationError("Memória inválida ou acima de 1200 caracteres.")
        return text

    def _transaction(self, callback):
        with self._lock:
            if self._connection is None:
                raise DatabaseLifecycleError("Memória não foi inicializada.")
            try:
                with self._connection.cursor() as cursor:
                    result = callback(cursor)
                self._connection.commit()
                return result
            except psycopg.Error as exc:
                self._connection.rollback()
                raise MemoryStoreError("Falha na operação de memória PostgreSQL.") from exc
            except Exception:
                self._connection.rollback()
                raise

    @staticmethod
    def _audit(cursor, action: str, memory_id=None, count: int = 0):
        cursor.execute(
            "INSERT INTO nexus_memory_audit (action, memory_id, affected_count) "
            "VALUES (%s, %s, %s)",
            (action, memory_id, count),
        )

    def _prune(self, cursor) -> int:
        cursor.execute("DELETE FROM nexus_memories WHERE expires_at <= CURRENT_TIMESTAMP")
        expired = cursor.rowcount
        if expired:
            self._audit(cursor, "EXPIRE", count=expired)
        return expired

    def purge_expired(self) -> int:
        return self._transaction(lambda cursor: self._prune(cursor))

    def add(self, content: str, retention_days: int = DEFAULT_RETENTION_DAYS) -> MemoryEntry:
        text = self._validate_content(content)
        days = self._positive_int(retention_days, "Prazo de retenção", self.MAX_RETENTION_DAYS)

        def action(cursor):
            self._prune(cursor)
            cursor.execute(
                "INSERT INTO nexus_memories (content, expires_at) "
                "VALUES (%s, CURRENT_TIMESTAMP + (%s * INTERVAL '1 day')) "
                "RETURNING id, content, created_at, expires_at",
                (text, days),
            )
            row = cursor.fetchone()
            entry = MemoryEntry.from_row(row)
            self._audit(cursor, "ADD", memory_id=entry.id, count=1)
            return entry

        return self._transaction(action)

    def list_entries(self, limit: int = 25) -> list[MemoryEntry]:
        max_rows = self._positive_int(limit, "Limite", self.MAX_RESULTS)

        def action(cursor):
            self._prune(cursor)
            cursor.execute(
                "SELECT id, content, created_at, expires_at FROM nexus_memories "
                "WHERE expires_at > CURRENT_TIMESTAMP ORDER BY id DESC LIMIT %s",
                (max_rows,),
            )
            rows = cursor.fetchall()
            self._audit(cursor, "LIST", count=len(rows))
            return [MemoryEntry.from_row(row) for row in rows]

        return self._transaction(action)

    def search(self, query: str, limit: int = 25) -> list[MemoryEntry]:
        term = self._validate_content(query)
        max_rows = self._positive_int(limit, "Limite", self.MAX_RESULTS)
        # PostgreSQL LIKE uses backslash as the escape character by default:
        # literal %, _ and backslash in a user query cannot become wildcards.
        escaped = term.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")

        def action(cursor):
            self._prune(cursor)
            cursor.execute(
                "SELECT id, content, created_at, expires_at FROM nexus_memories "
                "WHERE expires_at > CURRENT_TIMESTAMP AND content ILIKE %s "
                "ORDER BY id DESC LIMIT %s",
                (f"%{escaped}%", max_rows),
            )
            rows = cursor.fetchall()
            self._audit(cursor, "SEARCH", count=len(rows))
            return [MemoryEntry.from_row(row) for row in rows]

        return self._transaction(action)

    def delete(self, memory_id: int) -> bool:
        identifier = self._positive_int(memory_id, "Identificador")

        def action(cursor):
            self._prune(cursor)
            cursor.execute("DELETE FROM nexus_memories WHERE id = %s", (identifier,))
            deleted = cursor.rowcount > 0
            self._audit(cursor, "DELETE", memory_id=identifier, count=int(deleted))
            return deleted

        return self._transaction(action)

    def clear(self) -> int:
        def action(cursor):
            self._prune(cursor)
            cursor.execute("DELETE FROM nexus_memories")
            count = cursor.rowcount
            self._audit(cursor, "CLEAR", count=count)
            return count

        return self._transaction(action)

    def stats(self) -> dict[str, int]:
        def action(cursor):
            self._prune(cursor)
            cursor.execute(
                "SELECT COUNT(*) FROM nexus_memories WHERE expires_at > CURRENT_TIMESTAMP"
            )
            total = int(cursor.fetchone()[0])
            cursor.execute("SELECT COUNT(*) FROM nexus_memory_audit")
            audit_count = int(cursor.fetchone()[0])
            self._audit(cursor, "STATUS")
            return {"active": total, "audit_events": audit_count + 1}

        return self._transaction(action)
